# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "pr" do |pr|
    pr.vm.box = "generic/ubuntu2204"
    # pr.vm.network "public_network", ip: "192.168.0.200"
    pr.vm.network "private_network", type: "dhcp"
  end
  config.vm.define "pub" do |pub|
    pub.vm.box = "generic/ubuntu2204"
    # pub.vm.network "public_network", ip: "192.168.0.201"
    pub.vm.network "private_network", type: "dhcp"
  end
end
