@Library('jakas') _

def zmienna = tmp("string")
def czy = czy()
set()

pipeline {
    agent any
    stages {
        stage('1') {
            when {
                environment name: 'OPCJA', value: 'false'
            }
            steps {
                noop()
                echo zmienna['k1']

            }
        }
        stage('2') {
            when {
                expression { czy }
            }
            steps {
                echo "drugi"
            }
        }
        stage('3') {
            steps {
                echo los()
            }
        }

    }
}
