custom_fields1 = {
[(44,
  {'@odata.context': 'http://api.hellohq.io/v1/$metadata#CustomFields',
   'value': [{'Name': 'Informationen',
     'Value': '',
     'Type': 'TextMultiline',
     'Id': 18020,
     'CreatedBy': 0,
     'UpdatedBy': 0,
     'CreatedOn': None,
     'UpdatedOn': None},
    {'Name': 'GPP',
     'Value': 'Ja',
     'Type': 'DropdownCheckbox',
     'Id': 18049,
     'CreatedBy': 0,
     'UpdatedBy': 0,
     'CreatedOn': None,
     'UpdatedOn': None}]}),
 (45,
  {'@odata.context': 'http://api.hellohq.io/v1/$metadata#CustomFields',
   'value': [{'Name': 'Informationen',
     'Value': '',
     'Type': 'TextMultiline',
     'Id': 18020,
     'CreatedBy': 0,
     'UpdatedBy': 0,
     'CreatedOn': None,
     'UpdatedOn': None},
    {'Name': 'GPP',
     'Value': 'Ja',
     'Type': 'DropdownCheckbox',
     'Id': 18049,
     'CreatedBy': 0,
     'UpdatedBy': 0,
     'CreatedOn': None,
     'UpdatedOn': None}]}),
 (46,
  {'@odata.context': 'http://api.hellohq.io/v1/$metadata#CustomFields',
   'value': [{'Name': 'Informationen',
     'Value': '',
     'Type': 'TextMultiline',
     'Id': 18020,
     'CreatedBy': 0,
     'UpdatedBy': 0,
     'CreatedOn': None,
     'UpdatedOn': None},
    {'Name': 'GPP',
     'Value': 'Nein',
     'Type': 'DropdownCheckbox',
     'Id': 18049,
     'CreatedBy': 0,
     'UpdatedBy': 0,
     'CreatedOn': None,
     'UpdatedOn': None}]}))]
