--- #
- hosts: docker
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Install git
      package:
        name: git
        state: present
      become: yes

    - name: Create app directory for nvim
      file: 
        state: directory
        path: "{{ appDir }}"

    - name: Download nvim.appimage
      get_url:
        url: "{{ url }}"
        dest: "{{ nvimApp }}"
        mode: 777

    - name: Add path variable for nvim
      block:
        - shell: "grep {{appDir}} ~/.profile"
          register: grep_output
          failed_when: false
          no_log: true
        - lineinfile:
            path: ~/.profile
            line: "export PATH=$PATH:{{ appDir }}"
          when: grep_output.stderr == ""

    - name: Add nvim as default for vim
      block:
        - name: Add nvim as default for vim
          alternatives:
            name: vim
            path: "{{ nvimApp }}"
            link: /usr/bin/vim
            priority: 60
        - name: Add nvim as default for vim
          alternatives:
            name: vim
            path: "{{ nvimApp }}"
      become: yes

    - name: Add nvim as default for editor
      block:
        - name: Add nvim as default for editor
          alternatives:
            name: editor
            path: "{{ nvimApp }}"
            link: /usr/bin/editor
            priority: 60
        - name: Add nvim as default for editor
          alternatives:
            name: editor
            path: "{{ nvimApp }}"
      become: yes

    - name: Make sure {{ hostDir }} exists
      file:
        path: "{{ hostDir }}"
        state: directory

    - name: Copy neovim configuration
      copy:
        src: "{{ localDir }}/{{ item }}"
        dest: "{{ hostDir }}/"
      with_items:
        - init.vim
        - vimrc_parts
        - colors
        - ftplugin
        - UltiSnips
        - vimwiki

    - name: Make sure python3-venv is installed
      package:
        name: python3-venv
        state: present
      become: yes

    - name: Setup python support
      pip:
        name: neovim
        virtualenv: $HOME/neovim
        virtualenv_command: "{{ ansible_python_interpreter }} -m venv"

    - name: Install plugins
      shell: "vim +PlugInstall +qall > /dev/null"

    - name: Install COC
      block:
        - shell: '{{ nvimApp }} "+CocInstall coc-python" +qall > /dev/null'
        - copy:
            src: "{{ localDir }}/coc-settings.json"
            dest: "{{ hostDir }}/coc-settings.json"
